---
title: Your Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Your description

'
baseurl: https://richpar3.github.io/Palabra_Miel_Orlando/
url: https://github.com/richpar3/Palabra_Miel_Orlando.git
markdown: kramdown
facebook:
  app_id: 
logo: "../css/2016_style/img/icon-large.png"
social:
- title: facebook
  url: https://www.facebook.com
- title: twitter
  url: https://twitter.com
google_site_verification: googleXXXXXXXXXXXXXXXX.html
include:
- _2016_pages
- _2017_pages
gems:
- jekyll-sitemap
- jekyll-seo-tag
permalink: pretty
